<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="MAIN" Id="{56759815-ea35-437a-b440-8697e57be05b}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	a : INT;
	b : INT;
	c : INT;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[c := a+b;
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="10" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>